package com.ds.localtaskmanager.ui.today

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.widthIn
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.lazy.rememberLazyListState
import androidx.compose.material3.Button
import androidx.compose.material3.Card
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Scaffold
import androidx.compose.material3.SnackbarHost
import androidx.compose.material3.SnackbarHostState
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableFloatStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.rememberUpdatedState
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.input.nestedscroll.NestedScrollConnection
import androidx.compose.ui.input.nestedscroll.nestedScroll
import androidx.compose.ui.platform.LocalClipboardManager
import androidx.compose.ui.platform.LocalDensity
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.AnnotatedString
import androidx.compose.ui.unit.Velocity
import androidx.compose.ui.unit.dp
import com.ds.localtaskmanager.sharing.GeneratedShareImage
import com.ds.localtaskmanager.sharing.ResultShareTaskFilter
import com.ds.localtaskmanager.sharing.ShareImageService
import com.ds.localtaskmanager.ui.result.ResultGroupPresentation
import com.ds.localtaskmanager.ui.result.ResultTaskPresentation
import com.ds.localtaskmanager.ui.result.formatPoints
import com.ds.localtaskmanager.ui.result.toPlainText
import com.ds.localtaskmanager.ui.result.toPresentation
import com.ds.localtaskmanager.ui.sharing.SharePreviewDialog
import com.ds.localtaskmanager.ui.navigation.predictiveBackTransform
import com.ds.localtaskmanager.ui.navigation.rememberPredictiveBackState
import kotlinx.coroutines.launch

@Composable
fun TodayResultScreen(
    state: TodayResultUiState,
    shareService: ShareImageService,
    onRetry: () -> Unit,
    onClose: () -> Unit,
) {
    val snapshot = state.snapshot
    val presentation = remember(snapshot) { snapshot?.toPresentation() }
    val clipboard = LocalClipboardManager.current
    val scope = rememberCoroutineScope()
    val snackbar = remember { SnackbarHostState() }
    var generated by remember { mutableStateOf<GeneratedShareImage?>(null) }
    var generating by remember { mutableStateOf(false) }
    val predictiveBack = rememberPredictiveBackState(enabled = generated == null, onBack = onClose)

    Scaffold(
        modifier = Modifier.predictiveBackTransform(predictiveBack),
        snackbarHost = { SnackbarHost(snackbar) },
        bottomBar = {
            if (presentation != null) {
                Row(
                    modifier = Modifier.fillMaxWidth().padding(16.dp),
                    horizontalArrangement = Arrangement.spacedBy(12.dp),
                ) {
                    Button(
                        onClick = {
                            clipboard.setText(AnnotatedString(presentation.toPlainText()))
                            scope.launch { snackbar.showSnackbar("结果已复制") }
                        },
                        modifier = Modifier.weight(1f),
                    ) { Text("复制结果") }
                    Button(
                        onClick = {
                            scope.launch {
                                generating = true
                                runCatching { shareService.generateResult(requireNotNull(snapshot)) }
                                    .onSuccess { generated = it }
                                    .onFailure { snackbar.showSnackbar(it.message ?: "暂时无法生成图片") }
                                generating = false
                            }
                        },
                        enabled = !generating,
                        modifier = Modifier.weight(1f),
                    ) { Text("分享图片") }
                }
            }
        },
    ) { padding ->
        when {
            state.loading -> Box(Modifier.fillMaxSize().padding(padding), contentAlignment = Alignment.Center) { CircularProgressIndicator() }
            state.error != null -> ResultError(onRetry, onClose, Modifier.padding(padding))
            presentation == null -> ResultEmpty(onClose, Modifier.padding(padding))
            else -> ResultContent(presentation, onClose, Modifier.padding(padding))
        }
    }

    generated?.let { image ->
        SharePreviewDialog(
            image = image,
            service = shareService,
            sensitive = false,
            onResultFilterChange = { filter: ResultShareTaskFilter ->
                shareService.generateResult(requireNotNull(snapshot), filter)
            },
            onDismiss = { generated = null },
        )
    }
}

@Composable
internal fun ResultContent(
    result: com.ds.localtaskmanager.ui.result.ResultPresentation,
    onClose: () -> Unit,
    modifier: Modifier = Modifier,
    previewMode: Boolean = false,
) {
    val listState = rememberLazyListState()
    val threshold = with(LocalDensity.current) { 72.dp.toPx() }
    var closeDistance by remember { mutableFloatStateOf(0f) }
    val close by rememberUpdatedState(onClose)
    val connection = remember(threshold, listState) {
        object : NestedScrollConnection {
            override fun onPostScroll(consumed: Offset, available: Offset, source: androidx.compose.ui.input.nestedscroll.NestedScrollSource): Offset {
                if (!listState.canScrollForward && available.y < 0) {
                    closeDistance = (closeDistance - available.y * 0.55f).coerceAtMost(threshold * 1.25f)
                }
                return Offset.Zero
            }

            override suspend fun onPreFling(available: Velocity): Velocity {
                if (closeDistance >= threshold) close()
                closeDistance = 0f
                return Velocity.Zero
            }
        }
    }
    Box(modifier.fillMaxSize().testTag("today-result-content"), contentAlignment = Alignment.TopCenter) {
        if (previewMode) {
            Column(
                Modifier.fillMaxSize().widthIn(max = 720.dp).verticalScroll(rememberScrollState()).padding(20.dp),
                verticalArrangement = Arrangement.spacedBy(14.dp),
            ) {
                ResultHeader(result)
                result.groups.forEach { ResultGroupCard(it) }
                ResultCloseHint(closeDistance, threshold)
            }
        } else {
        LazyColumn(
            state = listState,
            modifier = Modifier.fillMaxSize().widthIn(max = 720.dp).nestedScroll(connection),
            contentPadding = PaddingValues(20.dp),
            verticalArrangement = Arrangement.spacedBy(14.dp),
        ) {
            item {
                ResultHeader(result)
            }
            items(result.groups, key = ResultGroupPresentation::name) { ResultGroupCard(it) }
            item {
                ResultCloseHint(closeDistance, threshold)
            }
        }
        }
    }
}

@Composable
private fun ResultHeader(result: com.ds.localtaskmanager.ui.result.ResultPresentation) {
    Column {
        Text("今日结果", style = MaterialTheme.typography.headlineLarge)
        result.domName?.let { Text("来自 $it", color = MaterialTheme.colorScheme.onSurfaceVariant) }
        Text(result.dateLabel, color = MaterialTheme.colorScheme.onSurfaceVariant)
        Spacer(Modifier.height(12.dp))
        Text(result.status, color = resultStatusColor(result.status), style = MaterialTheme.typography.titleLarge)
        Text("本日总积分 ${formatPoints(result.totalPoints)}", style = MaterialTheme.typography.titleMedium)
    }
}

@Composable
private fun ResultCloseHint(distance: Float, threshold: Float) {
    Text(
        if (distance >= threshold) "松手返回今日" else "继续上滑返回今日",
        modifier = Modifier.fillMaxWidth().padding(vertical = 24.dp),
        color = MaterialTheme.colorScheme.primary,
        style = MaterialTheme.typography.labelLarge,
    )
}

@Composable
private fun ResultGroupCard(group: ResultGroupPresentation) {
    Card(Modifier.fillMaxWidth()) {
        Column(Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) {
            Text(group.name, style = MaterialTheme.typography.titleLarge)
            Text("${group.status} · 净积分 ${formatPoints(group.points)}", color = resultStatusColor(group.status))
            group.tasks.forEach { ResultTaskRow(it) }
            group.message?.let { Text(it, color = MaterialTheme.colorScheme.onSurfaceVariant) }
        }
    }
}

@Composable
private fun ResultTaskRow(task: ResultTaskPresentation) {
    Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(12.dp)) {
        Column(Modifier.weight(1f)) {
            Text(task.name, style = MaterialTheme.typography.titleMedium)
            Text("${task.requirement} · ${task.status}", color = MaterialTheme.colorScheme.onSurfaceVariant)
        }
        Text(formatPoints(task.points), color = resultStatusColor(task.status))
    }
}

@Composable
internal fun ResultEmpty(onClose: () -> Unit, modifier: Modifier = Modifier) {
    Column(modifier.fillMaxSize().padding(32.dp), verticalArrangement = Arrangement.Center, horizontalAlignment = Alignment.CenterHorizontally) {
        Text("今天还没有可生成的结果", style = MaterialTheme.typography.titleLarge)
        TextButton(onClick = onClose) { Text("返回今日") }
    }
}

@Composable
private fun ResultError(onRetry: () -> Unit, onClose: () -> Unit, modifier: Modifier = Modifier) {
    Column(modifier.fillMaxSize().padding(32.dp), verticalArrangement = Arrangement.Center, horizontalAlignment = Alignment.CenterHorizontally) {
        Text("暂时无法生成今日结果", style = MaterialTheme.typography.titleLarge)
        Button(onClick = onRetry) { Text("重试") }
        TextButton(onClick = onClose) { Text("返回今日") }
    }
}

@Composable
private fun resultStatusColor(status: String): Color = when (status) {
    "全部完成", "已完成" -> MaterialTheme.colorScheme.primary
    "尚未完成", "待完成" -> MaterialTheme.colorScheme.secondary
    "有任务未完成", "未完成" -> MaterialTheme.colorScheme.error
    else -> MaterialTheme.colorScheme.onSurfaceVariant
}
